`for_each_n` doc completed (#3933)
MicrosoftDocs/cpp-docs pull request #3934
Opened 2022-05-30 00:14 UTC by BrandonPacewic

This pr fixes #3933. Adding documentation for the STL algorithm `for_each_n`.

2022-05-30 00:14 UTC, PRMerger8 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-30 00:17 UTC, PRMerger4 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-30 00:24 UTC, PRMerger4 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-30 01:14 UTC, PRMerger7 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-30 16:18 UTC, jborsecnik commented
@TylerMSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged"

2022-05-31 17:48 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +    for_each ( v1.begin( ), v1.end( ), MultValue<int> ( 5 ) );
Hi, our style is to not have the extra spacing between parens.

2022-05-31 18:07 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +    for ( i = -4 ; i <= 2 ; i++ )
Our style here, since `i` is not used outside the loop, is to limit its scope to where it is used and write: `for (int i = -4;` ...

2022-05-31 18:09 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +
This example requires /std:c++20  We should call that out.

2022-05-31 18:09 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +    cout << ")." << endl;
This function returns an int. We should return 0;

2022-05-31 18:22 UTC, TylerMSFT requested changes
@BrandonPacewic, thank you so much for seeing this hole and patching it up! Really appreciate you improving the docs.
I left some minor comments for you to consider.

2022-05-31 18:22 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +A signed or unsigned integral type specifying the number of elements to be operated on.
The detail is correct but it may be more consumable to simply say 'The number of elements to operate on'

2022-05-31 18:49 UTC, strega-nil requested changes
(accidentally reviewing from my personal account sorry lol)

2022-05-31 19:11 UTC, PRMerger14 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 19:13 UTC, PRMerger-2 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 19:26 UTC, PRMerger3 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 19:27 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +
@strega-nil: Sorry, it won't compile as written with the default C++14 that Visual Studio console projects use. So we should say at least /std:c++17

2022-05-31 19:55 UTC, BrandonPacewic commented
@TylerMSFT I am now ready for a re-review. I asked some clarifying questions about some suggestions. Also the more I look at my example the more I don't like it. I tried to make it similar to other examples but a lot of them are very outdated. Should I rewrite it in a more modern style similar to the newer docs?

2022-05-31 21:53 UTC, StephanTLavavej commented on docs/standard-library/algorithm-functions.md
> +    cout << ")." << endl;
Suggestion: The code to print the vector's elements surrounded by parentheses is repeated 3 times - this makes it harder to see the interesting work that the example is doing. Extracting this to a `print_vector()` function would improve clarity.

2022-05-31 21:53 UTC, StephanTLavavej commented on docs/standard-library/algorithm-functions.md
> +    for_each_n(pos, 4, MultValue<int>(-3));
Comment typo: This says "the next 3 elements" but it's operating on the next 4 elements.

2022-05-31 21:58 UTC, StephanTLavavej commented
Regarding lambdas, my feeling is that they would obscure the article's point. (That is, one should try to avoid teaching more than one major new idea at a time.) If someone has to read documentation for `for_each_n()`, which is one of the simplest STL algorithms, they are probably quite new to containers, iterators, algorithms, and function objects. The `MultValue` class with a data member and function call operator makes its behavior easier to understand - at the cost of verbosity, of course. Lambdas are shorter, which is why we use them in production code, but they involve a lot of magic happening behind the scenes, and that magic would distract from the simplicity of the algorithm invoking the function object.

However, it would be reasonable to mention at the end, something like "This example depicted a user-defined function object class, but production code often uses lambdas to achieve the same result with less code", linking to the topic about lambdas.

2022-05-31 22:16 UTC, PRMerger15 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 22:22 UTC, PRMerger20 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 22:30 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +    for (typename vector<int>::const_iterator iter = vec.begin(); iter != vec.end(); iter++)
suggest using auto to hide the iterator type complexity, which isn't germane to the example

2022-05-31 22:31 UTC, BrandonPacewic commented
Example looks better now unless anyone has a problem with how I wrote the `print_vector` function, perhaps it should only expect a `vector<int>` instead of a templated vector? I avoided the `auto` keyword but it might make it easier to understand.

The wording I used for the params is almost identical to the `fill_n` function. Should it be changed to make it easier to read? It is possible that I am making a mistake by trying to use the older documentation as a guide.

2022-05-31 22:33 UTC, TylerMSFT requested changes
Hi Brandon,
Thank you for hanging in there on this. Thank you for the updates so far. I agree with the comment Stephan made about the lambdas. I'll watch for the update addressing that, and then we'll see if we can get this through.

Oh, regarding using the older documentation as a guide, yes, things have evolved. The difficulty is that we have hundreds of topics that are older than some of the people who come here to use them. We'd like to update them all, but simply don't have the resources. So, we go through what you are going through now, which is trying to make a little corner of the C++ docs better than it was before :-)

2022-05-31 22:34 UTC, PRMerger12 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 22:48 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +uses [`lambda`](https://docs.microsoft.com/en-us/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170)s to achieve the same result with less code
Could you take the en-us out of the link? It causes the link to not go to the language specific version (our docs are translated into other languages).

2022-05-31 22:49 UTC, TylerMSFT commented on docs/standard-library/algorithm-functions.md
> +Example requires `c++17`
Maybe do this by using the // compile with: /EHsc line and add the new flag, e.g.
// compile with /EHsc and /std:c++17 (or higher)

2022-05-31 22:58 UTC, PRMerger20 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 23:08 UTC, TylerMSFT approved these changes
@BrandonPacewic, thank you for making this contribution to the docs. I realize that you are doing it out of good will and on your own time. Thank you for improving this doc and participating in going back and forth with us on it.

2022-05-31 23:09 UTC, PRMerger15 commented
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-31 23:09 UTC, BrandonPacewic commented
That's my last change I promise :smiley_cat:

2022-05-31 23:10 UTC, TylerMSFT commented
#sign-off

2022-05-31 23:17 UTC, BrandonPacewic commented
> @BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

I love working on these types of things. It is no burden for me to write back and forth. I sincerely appreciate everyone's willingness to work with me! :heart:

2022-05-31 23:48 UTC, TylerMSFT approved these changes
Re-approving - getting a request to do so for some reason.

2022-05-31 23:50 UTC, BrandonPacewic commented
I made one more commit a few seconds after you approved the changes

2022-05-31 23:52 UTC, TylerMSFT commented
#sign-off

2022-06-01 15:21 UTC, ShannonLeavitt commented on docs/standard-library/algorithm-functions.md
> +uses [`lambda`](https://docs.microsoft.com/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170)s to achieve the same result with less code
```suggestion
This example depicts a user-defined function object class. Production code often
uses [`lambda`](https://docs.microsoft.com/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170)s to achieve the same result with less code.
```
Edits to punctuation

2022-06-01 15:21 UTC, PRMerger5 commented
@ShannonLeavitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-06-01 15:22 UTC, merged

2022-06-01 21:55 UTC, wadepickett commented
Hey @BrandonPacewic , great work!

2022-06-01 22:03 UTC, BrandonPacewic commented
> Hey @BrandonPacewic , great work!

Thanks! 😺

2022-06-02 16:59 UTC, TylerMSFT commented
@BrandonPacewic , I sent you an e-mail a few minutes ago. Check your junk mail because it'll probably go there :-)