Fixed inconsistent spelling of "newline"
MicrosoftDocs/cpp-docs pull request #4104
Opened 2022-08-19 04:52 UTC by weijuwang

"newline" was spelled as "new-line" two out of four times in the documentation.

2022-08-19 04:54 UTC, opbld33 commented
Docs Build status updates of commit _[aa9156b](https://github.com/weijuwang/cpp-docs/commits/aa9156bc0e15a84d92c0e96d23d241385b7b9c8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/c-language/lexical-grammar.md](https://github.com/weijuwang/cpp-docs/blob/patch-1/docs/c-language/lexical-grammar.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/813c26e3-f1ed-5796-cab4-24adc659812f/202208190452244669-4104/BuildReport?accessString=a9026d23e2c848984d932d57cc766348aa5754b1fe5894eb6519387ea0d80f81).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/813c26e3-f1ed-5796-cab4-24adc659812f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 15:03 UTC, Jak-MS commented
@corob-msft - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2022-08-20 00:59 UTC, corob-msft requested changes
@weijuwang 
Thanks for pointing out the inconsistency and proposing a fix. You have the right idea, but you've fixed the wrong targets. Ordinarily, I'd accept this PR, because the common term we use in the rest of the documentation is "newline". However, the [C lexical grammar](https://docs.microsoft.com/cpp/c-language/lexical-grammar?view=msvc-170) page quotes Annex A of the [C17 Standard](https://web.archive.org/web/20181230041359if_/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf), which uses "new-line" everywhere. To be consistent, we should change the two cases of "newline" to "new-line". I'll approve and merge the PR if you make those changes. Thank you again for taking the time to make the docs better.

2022-08-20 01:46 UTC, weijuwang commented
Should be fixed now. Thanks for the response!

2022-08-20 01:46 UTC, opbld32 commented
Docs Build status updates of commit _[2bc0468](https://github.com/weijuwang/cpp-docs/commits/2bc0468334115773d24782f54b8195070e53b55d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/c-language/lexical-grammar.md](https://github.com/weijuwang/cpp-docs/blob/patch-1/docs/c-language/lexical-grammar.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/813c26e3-f1ed-5796-cab4-24adc659812f/202208200144386435-4104/BuildReport?accessString=74f932fe744e53fe03af37dd592eabe88b3f973805fa70ab91a33685526b0d5b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/813c26e3-f1ed-5796-cab4-24adc659812f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-20 02:30 UTC, corob-msft approved these changes
Looks good to me. Thanks for the quick turnaround, @weijuwang

2022-08-20 02:30 UTC, merged