add a code example to how-to-create-and-use-shared-ptr-instances.md
MicrosoftDocs/cpp-docs pull request #4546
Opened 2023-05-13 11:34 UTC by fsb4000

Fixes #4461

2023-05-15 15:21 UTC, Court72 commented
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-05-25 23:30 UTC, TylerMSFT requested changes
Please update the date of the article since a meaningful change is happening. It helps us with our tools that track freshness.

2023-05-26 17:48 UTC, TylerMSFT approved these changes

2023-05-26 17:49 UTC, TylerMSFT approved these changes

2023-05-26 20:12 UTC, CaseyCarter commented on docs/cpp/codesnippet/CPP/how-to-create-and-use-shared-ptr-instances_5.cpp
> +}
Is it worth adding another line at the end with `use_shared_ptr_by_value(std::move(sp))` which doesn't increment the reference count but in fact transfers ownership to the callee?

2023-05-26 22:15 UTC, TylerMSFT requested changes
Please makes the updates that Casey suggested, then we should be good to go.

2023-05-30 19:39 UTC, TylerMSFT approved these changes
This is great - thank you @fsb4000

2023-05-30 19:39 UTC, TylerMSFT commented
#sign-off

2023-05-30 19:50 UTC, CaseyCarter approved these changes

2023-05-30 19:50 UTC, CaseyCarter commented on docs/cpp/codesnippet/CPP/how-to-create-and-use-shared-ptr-instances_5.cpp
> +}
Thanks, @fsb4000, this looks great.

2023-05-30 20:53 UTC, merged