[link.exe /INTEGRITYCHECK] fix -- ":NO" suffix doesn't work, so update the docs
MicrosoftDocs/cpp-docs pull request #4676
Opened 2023-08-09 10:54 UTC by glenn-slayden

The doc mentions `/INTEGRITYCHECK:NO`, but this does not appear to be a valid command line option with the current `link.exe` releases. My version of `link` rejects that syntax entirely.

I don't know where the official `link.exe` source code is kept, but it likely has the exact same bug in the code that I found in the link below. Due to this obvious bug that I point out in the source code, there seems to be no way to explicilty assert `/INTEGRITYCHECK` in the negative, except by simply removing the option. 

https://github.com/microsoft/BuildXL/blob/main/Public/Sdk/Experimental/Msvc/Native/Tools/Link/Link.dsc#L303-L307

I would welcome a `link` developer to fix the program itself, so it works as described, but in the meantime, at least the docs can be changed to reflect the current situation.

2023-08-09 10:55 UTC, glenn-slayden commented
c.f. oops... https://github.com/glenn-slayden/cpp-docs/pull/1

2023-08-09 14:49 UTC, Court72 commented
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-08-09 17:04 UTC, TylerMSFT commented
Thanks, @glenn-slayden.  I'll take this up with a dev on the linker team and see what direction they'd like to go.

2023-08-11 17:52 UTC, TylerMSFT commented
The dev who works on the linker went through the source code history, and sees no evidence of it ever supporting the :NO portion. So that's a strange doc artifact, that your update fixes. Thank you!

2023-08-11 17:55 UTC, TylerMSFT requested changes
See what you think of the small suggestion I made. What I'm trying to avoid is people thinking the feature is somehow on unless they do something.

2023-08-11 17:55 UTC, TylerMSFT commented on docs/build/reference/integritycheck-require-signature-check.md
> +1. To disable the feature, remove the *`/INTEGRITYCHECK`* option.
This might be slightly clearer if we say "This feature is off unless turned on with `/INTEGRITYCHECK`."

2023-08-11 19:44 UTC, TylerMSFT commented on docs/build/reference/integritycheck-require-signature-check.md
> +1. To disable the feature, remove the *`/INTEGRITYCHECK`* option.
I updated this. If you have something you'd like better, let me know. In the meantime I'll get your changes through.

2023-08-11 19:45 UTC, TylerMSFT approved these changes

2023-08-11 20:07 UTC, TylerMSFT commented
#sign-off

2023-08-11 20:56 UTC, merged

2023-08-29 18:26 UTC, glenn-slayden commented
@TylerMSFT  Sorry for the late remark after this is closed, but my original text was also not the best:

" &bull; To build an image which requires digital signature verification **_in order_** to be loaded,..."

...would be slightly less ambiguous. It would avoid the incorrect/nonsensical reading where it is somehow the "verification" (as opposed to, correctly, the _image_) which must be "loaded".

2023-08-29 23:40 UTC, TylerMSFT commented
No worries, @glenn-slayden. I don't actually that sentence the way you do, but since I'm in this folder today, anyway, I tweaked it like so:
1. To create a digitally-signed image, include `/INTEGRITYCHECK` in the **Additional Options** command line. A digitally-signed image must pass a verification check before it is loaded. This feature is disabled by default.

2023-08-31 08:08 UTC, glenn-slayden commented
Super, thanks.