Add example to C3550
MicrosoftDocs/cpp-docs pull request #4754
Opened 2023-10-06 18:50 UTC by Rageking8

The "dummy" int was added to reduce the number of compiler errors generated (to make the example more targeted), as omitting the return statement in those functions yielded a lot of compiler errors.

2023-10-06 21:14 UTC, Jak-MS commented
@t
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-10-17 22:37 UTC, TylerMSFT requested changes
Small request added

2023-10-17 22:37 UTC, TylerMSFT commented on docs/error-messages/compiler-errors-2/compiler-error-c3550.md
> +To resolve the error remove all illegal qualification on `decltype(auto)`.
Can you add a small example: For instance, `decltype(auto)* func1();` becomes `auto *func1();`

2023-10-31 18:04 UTC, TylerMSFT approved these changes
Thank you!

2023-10-31 20:40 UTC, merged

2023-10-31 20:40 UTC, Jak-MS commented
merged