Updating CMake Debugging Docs to have CMake Debugger
MicrosoftDocs/cpp-docs pull request #4778
Opened 2023-10-23 17:52 UTC by sinemakinci1

Adding CMake Debugger information and refreshing top-level screenshots

2023-10-23 20:49 UTC, TylerMSFT requested changes
Hi Sinem,
I sent you a mail about some ideas for alt-text.

2023-10-23 23:12 UTC, TylerMSFT reviewed
You are missing the :::image-end:::

2023-10-24 14:56 UTC, ShannonLeavitt commented
@TylerMSFT

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-10-24 22:43 UTC, sinemakinci1 commented
@TylerMSFT It should be good to review now, thank you for your help!

2023-10-25 22:24 UTC, TylerMSFT approved these changes
Thanks, Sinem!

2023-10-25 22:24 UTC, TylerMSFT commented
#sign-off

2023-10-26 14:14 UTC, Court72 commented on docs/build/configure-cmake-debugging-sessions.md
> +:::image type="complex" source="media/debug-targets-view.png" alt-text="Screenshot of the CMake Targets View debug option menu":::
```suggestion
:::image type="complex" source="media/debug-targets-view.png" alt-text="Screenshot of the CMake Targets View debug option menu.":::
```

2023-10-26 14:15 UTC, Court72 commented on docs/build/configure-cmake-debugging-sessions.md
> +Starting in Visual Studio 2022 Version 17.6, you can also start a debugging session on your CMakeLists.txt file. To do so, just set a breakpoint in your CMakeLists.txt file and run **Configure Projec
```suggestion
Starting in Visual Studio 2022 Version 17.6, you can also start a debugging session on your CMakeLists.txt file. To do so, just set a breakpoint in your CMakeLists.txt file and run **Configure Project with CMake Debugger** from the **Project** dropdown.
```

2023-10-26 14:15 UTC, Court72 commented on docs/build/configure-cmake-debugging-sessions.md
> +:::image type="complex" source="media/cmake-debugger-entry.png" alt-text="Screenshot of the CMake Debugger dropdown":::
```suggestion
:::image type="complex" source="media/cmake-debugger-entry.png" alt-text="Screenshot of the CMake Debugger dropdown.":::
```

2023-10-26 14:20 UTC, Court72 commented
Merging now.

2023-10-26 14:20 UTC, merged