Create warning directive page
MicrosoftDocs/cpp-docs pull request #4804
Opened 2023-11-08 10:20 UTC by Rageking8

Fixes #4703

2023-11-08 15:36 UTC, Court72 commented
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-02-14 00:37 UTC, TylerMSFT requested changes
Thank you. I'll hang onto this but won't send it through now because we don't support this directive yet.

2025-01-28 21:26 UTC, TylerMSFT commented
@RageKing8, I'm going through PRs and this feature still isn't implemented yet (as of 1/28/2025). I will come back to this once it is. I haven't forgotten it :-)

2025-07-15 20:43 UTC, v-dirichards commented
Closing/reopening to refresh the CLA status

2025-07-15 20:43 UTC, closed without merging

2025-09-02 21:41 UTC, v-dirichards commented
**These changes look ok from the PR Review team's perspective.**

2025-10-15 16:55 UTC, TylerMSFT commented
Excellent. I'll port this to the private repo, stage it, and get it published (a procedural thing since we don't add new topics from the public repo)
@Rageking8 - thank you very much for writing this topic up!

2025-10-15 17:19 UTC, TylerMSFT commented
Closing because I've ported this work to the private repo. I'll publish it from there.
See PR #6119